// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Test3
{
	public partial class OtherViewController : UIViewController
	{
		public OtherViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            btnGo.TouchUpInside += (object sender, EventArgs e) => 
            {
                DismissViewController(true, null);
            };
        }
	}
}
